apiVersion: v1
kind: Service
metadata:
  name: {{ include "poc-api.fullname" . }}-svc
  labels:
    {{- include "poc-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http-3000
  selector:
    {{- include "poc-api.selectorLabels" . | nindent 4 }}
