apiVersion: v1
kind: ConfigMap
metadata:
  name: front-config
data:
  config.js: |
    var config = (() => {
      return {
        "VITE_API_BASE_URL": "{{ .Values.appConfig.VITE_API_BASE_URL }}",
        "VITE_API_TODOS_PATH": "{{ .Values.appConfig.VITE_API_TODOS_PATH }}",
      };
    })();